### ISSUE TITLE
一款采用谷歌最新mvvm架构和Jetpack架构组件，kotlin 携程网络请求，Arouter组件化开发的干货集中营客户端

### ISSUE THREAD

**Issue by Victor2018** [AWCN/AndroidDevWeekly#1]
https://github.com/Victor2018/Cherry

Jetpack components such as paging ktx flow, aouter componentized development, kolin coroutines cooperate with retrofit network request, dry gank browsing, beautiful girls, live show watching. . . All you want is here.This application is only for learning and use.Please do not use it!

**Comment by inferjay** [comment]
已收录
